---
os: linux
dist: xenial

language: ruby
cache: bundler
rvm:
  - 2.7.1

services:
  - docker

env:
  jobs:
    - INSTANCE: default-debian-stretch
    - INSTANCE: default-debian-buster

script:
  - bin/kitchen verify ${INSTANCE}
