---
os: linux
dist: xenial

language: ruby
cache: bundler

services:
  - docker

env:
  matrix:
    - INSTANCE: default-debian-stretch
    - INSTANCE: default-debian-buster

script:
  - bin/kitchen verify ${INSTANCE}
